service: viewServer
provider:
  name: aws
  runtime: nodejs6.10
  region: us-west-1
package:
  individually: true
  exclude:
    - ./**
  include:
    - server.js
    - app.js
    - node_modules/**
functions:
  server:
    handler: server.handle
    environment:
      API_HOST: ${env:AWS_API_HOST}
      STATIC_ROOT: ${env:AWS_STATIC_ROOT}
    events:
      - http: ANY view/
      - http: ANY view/{route+}
plugins:
  - serverless-s3-assets
  - serverless-plugin-optimize
custom:
  s3Assets:
    static:
      bucket: ${env:AWS_S3_BUCKET}
      css:
        contentType: text/css
